AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  DoctorAILambdaMain:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: >-
        arn:aws:iam::817597399723:role/service-role/DoctorAI_Lambda_Main-role-ycdoiywo
      Layers:
        - 'arn:aws:lambda:us-east-1:817597399723:layer:neo4j:2'
