version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1sl9b81akteez"
s3_prefix = "sam-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
disable_rollback = true
image_repositories = []
parameter_overrides = "FrontendRepoURL=\"https://github.com/dgg32/doctorai-ui\" BotID=\"FEINSTMDCU\""
